@echo off
echo 正在修复所有页面的Toolbar...

echo 修复 farm_list.xml...
powershell -Command "(Get-Content 'app\src\main\res\layout\activity_farm_list.xml') -replace 'android:background=\"@color/material_dynamic_primary\"', 'android:background=\"@android:color/transparent\"' -replace 'app:title=\"[^\"]*\"', 'app:title=\"\"' -replace 'app:titleTextColor=\"@android:color/white\"', '' -replace 'app:navigationIconTint=\"@android:color/white\"', 'app:navigationIconTint=\"#4CAF50\"' | Set-Content 'app\src\main\res\layout\activity_farm_list.xml'"

echo 修复 farm_detail.xml...
powershell -Command "(Get-Content 'app\src\main\res\layout\activity_farm_detail.xml') -replace 'android:background=\"@color/material_dynamic_primary\"', 'android:background=\"@android:color/transparent\"' -replace 'app:title=\"[^\"]*\"', 'app:title=\"\"' -replace 'app:titleTextColor=\"@android:color/white\"', '' -replace 'app:navigationIconTint=\"@android:color/white\"', 'app:navigationIconTint=\"#4CAF50\"' | Set-Content 'app\src\main\res\layout\activity_farm_detail.xml'"

echo 修复 farm_point_detail.xml...
powershell -Command "(Get-Content 'app\src\main\res\layout\activity_farm_point_detail.xml') -replace 'android:background=\"@color/material_dynamic_primary\"', 'android:background=\"@android:color/transparent\"' -replace 'app:title=\"[^\"]*\"', 'app:title=\"\"' -replace 'app:titleTextColor=\"@android:color/white\"', '' -replace 'app:navigationIconTint=\"@android:color/white\"', 'app:navigationIconTint=\"#4CAF50\"' | Set-Content 'app\src\main\res\layout\activity_farm_point_detail.xml'"

echo 修复 company_info.xml...
powershell -Command "(Get-Content 'app\src\main\res\layout\activity_company_info.xml') -replace 'android:background=\"@color/material_dynamic_primary\"', 'android:background=\"@android:color/transparent\"' -replace 'app:title=\"[^\"]*\"', 'app:title=\"\"' -replace 'app:titleTextColor=\"@android:color/white\"', '' -replace 'app:navigationIconTint=\"@android:color/white\"', 'app:navigationIconTint=\"#4CAF50\"' | Set-Content 'app\src\main\res\layout\activity_company_info.xml'"

echo 修复 profile.xml...
powershell -Command "(Get-Content 'app\src\main\res\layout\activity_profile.xml') -replace 'android:background=\"@color/material_dynamic_primary\"', 'android:background=\"@android:color/transparent\"' -replace 'app:title=\"[^\"]*\"', 'app:title=\"\"' -replace 'app:titleTextColor=\"@android:color/white\"', '' -replace 'app:navigationIconTint=\"@android:color/white\"', 'app:navigationIconTint=\"#4CAF50\"' | Set-Content 'app\src\main\res\layout\activity_profile.xml'"

echo 修复 activity_environment_monitoring_enhanced.xml...
powershell -Command "(Get-Content 'app\src\main\res\layout\activity_environment_monitoring_enhanced.xml') -replace 'android:background=\"@color/material_dynamic_primary\"', 'android:background=\"@android:color/transparent\"' -replace 'app:title=\"[^\"]*\"', 'app:title=\"\"' -replace 'app:titleTextColor=\"@android:color/white\"', '' -replace 'app:navigationIconTint=\"@android:color/white\"', 'app:navigationIconTint=\"#4CAF50\"' | Set-Content 'app\src\main\res\layout\activity_environment_monitoring_enhanced.xml'"

echo 修复 activity_data_analysis_enhanced.xml...
powershell -Command "(Get-Content 'app\src\main\res\layout\activity_data_analysis_enhanced.xml') -replace 'android:background=\"@color/material_dynamic_primary\"', 'android:background=\"@android:color/transparent\"' -replace 'app:title=\"[^\"]*\"', 'app:title=\"\"' -replace 'app:titleTextColor=\"@android:color/white\"', '' -replace 'app:navigationIconTint=\"@android:color/white\"', 'app:navigationIconTint=\"#4CAF50\"' | Set-Content 'app\src\main\res\layout\activity_data_analysis_enhanced.xml'"

echo 所有Toolbar修复完成！
